### ISSUE TITLE
开始监听消息后，会发生以下报错，项目独立运行的时候是正常的，但是把项目部署到我自己的项目中调用运行，就会发生这样的报错，可以帮我看看是什么原因吗

### ISSUE THREAD

**Issue by ChrisYJH** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#111]
[09:15:45] [nioEventLoopGroup-2-1/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalAccessError: class tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.ImageOuterClass$Image tried to access method 'com.google.protobuf.LazyStringArrayList com.google.protobuf.LazyStringArrayList.emptyList()' (tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.ImageOuterClass$Image is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7a29d5ab; com.google.protobuf.LazyStringArrayList is in unnamed module of loader java.net.URLClassLoader @4ccabbaa)
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.ImageOuterClass$Image.<init>(ImageOuterClass.java:1556) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.ImageOuterClass$Image.<clinit>(ImageOuterClass.java:3615) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.UserOuterClass$User$Builder.getAvatarThumb(UserOuterClass.java:24805) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.UserOuterClass$User$Builder.getAvatarThumbFieldBuilder(UserOuterClass.java:24900) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.UserOuterClass$User$Builder.mergeFrom(UserOuterClass.java:23734) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.dto.UserOuterClass$User$Builder.mergeFrom(UserOuterClass.java:22342) ~[?:?]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:872) ~[protobuf-java-3.21.9.jar:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.douyin_webcast_member_message_msg$Builder.mergeFrom(douyin_webcast_member_message_msg.java:1273) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.douyin_webcast_member_message_msg$1.parsePartialFrom(douyin_webcast_member_message_msg.java:2800) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.douyin_webcast_member_message_msg$1.parsePartialFrom(douyin_webcast_member_message_msg.java:2792) ~[?:?]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:100) ~[protobuf-java-3.21.9.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:120) ~[protobuf-java-3.21.9.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125) ~[protobuf-java-3.21.9.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.21.9.jar:?]
	at tech.ordinaryroad.live.chat.client.douyin.protobuf.douyin_webcast_member_message_msg.parseFrom(douyin_webcast_member_message_msg.java:852) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.netty.handler.DouyinBinaryFrameHandler.onCmdMsg(DouyinBinaryFrameHandler.java:108) ~[?:?]
	at tech.ordinaryroad.live.chat.client.douyin.netty.handler.DouyinBinaryFrameHandler.onCmdMsg(DouyinBinaryFrameHandler.java:50) ~[?:?]
	at tech.ordinaryroad.live.chat.client.commons.base.listener.IBaseMsgListener.onCmdMsg(IBaseMsgListener.java:61) ~[?:?]
	at tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseBinaryFrameHandler.onCmdMsg(BaseBinaryFrameHandler.java:119) ~[?:?]
	at tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseBinaryFrameHandler.channelRead0(BaseBinaryFrameHandler.java:81) ~[?:?]
	at tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseBinaryFrameHandler.channelRead0(BaseBinaryFrameHandler.java:48) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:89) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1466) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1329) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1378) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by 1962247851** [comment]
看一下protobuf依赖有没有版本冲突

**Comment by 1962247851** [comment]
还有用的是哪个版本

**Comment by ChrisYJH** [comment]
jdk17, jdk21 都试过了

**Comment by ChrisYJH** [comment]
我在项目添加中了live-chat-client-douyin 0.4.4依赖，然后maven打包的时候就发生了这样的报错

- com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream
  - com.google.protobuf.AbstractMessageLite$InternalOneOfEnum
  - com.google.protobuf.AbstractParser
  - com.google.protobuf.AbstractProtobufList
  - com.google.protobuf.AllocatedBuffer
  - 736 more...
logback-classic-1.3.14.jar, spigottest-1.0.jar define 190 overlapping classes and resources: 
  - META-INF/maven/ch.qos.logback/logback-classic/pom.properties
  - META-INF/maven/ch.qos.logback/logback-classic/pom.xml
  - META-INF/services/javax.servlet.ServletContainerInitializer
  - META-INF/services/org.slf4j.spi.SLF4JServiceProvider
  - ch.qos.logback.classic.AsyncAppender
  - ch.qos.logback.classic.BasicConfigurator
  - ch.qos.logback.classic.ClassicConstants
  - ch.qos.logback.classic.Level
  - ch.qos.logback.classic.Logger
  - ch.qos.logback.classic.LoggerContext
  - 180 more...
logback-core-1.3.14.jar, spigottest-1.0.jar define 454 overlapping classes and resources: 
  - META-INF/maven/ch.qos.logback/logback-core/pom.properties
  - META-INF/maven/ch.qos.logback/logback-core/pom.xml
  - ch.qos.logback.core.Appender
  - ch.qos.logback.core.AppenderBase
  - ch.qos.logback.core.AsyncAppenderBase
  - ch.qos.logback.core.AsyncAppenderBase$Worker
  - ch.qos.logback.core.BasicStatusManager
  - ch.qos.logback.core.ConsoleAppender
  - ch.qos.logback.core.Context
  - ch.qos.logback.core.ContextBase
  - 444 more...
slf4j-api-2.0.7.jar, spigottest-1.0.jar define 53 overlapping classes and resources: 
  - META-INF/maven/org.slf4j/slf4j-api/pom.properties
  - META-INF/maven/org.slf4j/slf4j-api/pom.xml
  - org.slf4j.ILoggerFactory
  - org.slf4j.IMarkerFactory
  - org.slf4j.Logger
  - org.slf4j.LoggerFactory
  - org.slf4j.LoggerFactoryFriend
  - org.slf4j.MDC
  - org.slf4j.MDC$1
  - org.slf4j.MDC$MDCCloseable
  - 43 more...
maven-shade-plugin has detected that some class files are
present in two or more JARs. When this happens, only one
single version of the class is copied to the uber jar.
Usually this is not harmful and you can skip these warnings,
otherwise try to manually exclude artifacts based on
mvn dependency:tree -Ddetail=true and the above output.
See http://maven.apache.org/plugins/maven-shade-plugin/

**Comment by ChrisYJH** [comment]
![image](https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/31099950/9aed1396-8e50-4dac-9e2c-7f2bab3d3754)

**Comment by 1962247851** [comment]
老哥，报错里写的很清楚了，依赖冲突了

**Comment by 1962247851** [comment]
0.4.4使用的protobuf-java版本是3.25.3
<img width="394" alt="image" src="https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/43869694/b07351ad-2054-4ec4-a15c-6a89ab352f30">
报错里3.21.9
<img width="749" alt="image" src="https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/assets/43869694/09d1caf1-2b75-4df6-a88b-b401774c260a">

**Comment by ChrisYJH** [comment]
但是我的项目中并没有使用protobuf的依赖。。。

**Comment by 1962247851** [comment]
QQ频道：https://pd.qq.com/s/3id0n7fvs
