### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 727729853** [OrdinaryRoad-Project/ordinaryroad-live-chat-client#166]
`00:14:37.180 [nioEventLoopGroup-2-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
com.qq.tars.protocol.tars.exc.TarsDecodeException: type mismatch.`

平台：虎牙
情况：每隔一段时间就提示这个错的

**Comment by 727729853** [comment]
> `2024-12-02 21:51:15.614 [nioEventLoopGroup-5-1] WARN  io.netty.channel.DefaultChannelPipeline:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
com.qq.tars.protocol.tars.exc.TarsDecodeException: type mismatch.
	at com.qq.tars.protocol.tars.TarsInputStream.read(TarsInputStream.java:252)
	at tech.ordinaryroad.live.chat.client.codec.huya.msg.dto.ItemEffectBizData.readFrom(ItemEffectBizData.java:57)
	at com.qq.tars.protocol.tars.TarsInputStream.read(TarsInputStream.java:835)
	at com.qq.tars.protocol.tars.TarsInputStream.read(TarsInputStream.java:871)
	at com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl(TarsInputStream.java:789)
	at com.qq.tars.protocol.tars.TarsInputStream.readArray(TarsInputStream.java:772)
	at tech.ordinaryroad.live.chat.client.codec.huya.msg.SendItemSubBroadcastPacketMsg.readFrom(SendItemSubBroadcastPacketMsg.java:196)
	at tech.ordinaryroad.live.chat.client.codec.huya.msg.SendItemSubBroadcastPacketMsg.<init>(SendItemSubBroadcastPacketMsg.java:104)
	at tech.ordinaryroad.live.chat.client.huya.netty.handler.HuyaBinaryFrameHandler.onCmdMsg(HuyaBinaryFrameHandler.java:173)
	at tech.ordinaryroad.live.chat.client.huya.netty.handler.HuyaBinaryFrameHandler.onCmdMsg(HuyaBinaryFrameHandler.java:56)
	at tech.ordinaryroad.live.chat.client.commons.base.listener.IBaseMsgListener.onCmdMsg(IBaseMsgListener.java:59)
	at tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseBinaryFrameHandler.onCmdMsg(BaseBinaryFrameHandler.java:108)
	at tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseBinaryFrameHandler.channelRead0(BaseBinaryFrameHandler.java:79)
	at tech.ordinaryroad.live.chat.client.servers.netty.handler.base.BaseBinaryFrameHandler.channelRead0(BaseBinaryFrameHandler.java:46)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
.`
> 
> 平台：虎牙 情况：每隔一段时间就提示这个错的

**Comment by 1962247851** [comment]
可能是虎牙改了字段类型

**Comment by 1962247851** [comment]
> 可能是虎牙改了字段类型

好吧，是我写错了
<img width="584" alt="image" src="https://github.com/user-attachments/assets/68abe1a7-2d10-4235-9dc7-0828dc346341">
